import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/navbar/Nav";
import Footer from "./components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
           <div className="">
            {children}
            <Footer />
           </div>
        </body>
    </html>
  );
}
